spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/a?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zhangqian
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: shiro
#server:
#  servlet:
#    context-path: /shiro